---
title: "index"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

collison <- read.csv('data/SDOT_Collisions.csv')
```

## Exploring Seattle's Car Collisions


```{r map, warning=FALSE}
library('leaflet')
library('stringr')
library('dplyr')
## creates interactive map
pal <- colorFactor(c("navy", "red","blue","green","yellow"), domain = c("ship", "pirate"))
#qpal <- colorQuantile("RdYlBu", shooting.data$killed, n = 3)

# remove rows with missing data 
noNa = collison[complete.cases(collison),]

d = data.frame(str_split(as.character(noNa$Shape), " ") )



long = data.frame(unlist(d[2,]))
lat = data.frame(unlist(d[1,]))
names(lat) = "lat"
names(long) = "long"

lat = as.vector(lat$lat)
long = as.vector(long$long)


lat = str_replace(lat, "\\(",  "")
lat = str_replace(lat, "\\)",  "")
lat = str_replace(lat, "\\,",  "")

long = str_replace(long, "\\,",  "")
long = str_replace(long, "\\(",  "")
long = str_replace(long, "\\)",  "")

ma = data.frame(lat,long)

noNa$lat = as.numeric(paste(ma$lat))
noNa$lng = as.numeric(paste(ma$long))


sample =  sample_n(noNa, 500)


m <- leaflet(data = sample) %>%
  addTiles() %>% 
  addCircleMarkers(~lng, ~lat)



```
`r m`





